delta_data:
  base_path : 'data/scmp-raw-layer/cpo/cpis/ba_dmnd_data'
delta_table: 
  delta_table_path : "data/scmp-stage-layer/cpo/ba_dmnd_data_sdk_fulldata_mulcols"
  delta_table_source_path : "data/scmp-raw-layer/cpo/cpis/ba_dmnd_data/year=2024/month=7/day=30/ba_dmnd_data_20240730_mulcols.parquet"
