delta_data:
  base_path : 'data/scmp-raw-layer/cpo/cpis/ba_dmnd_data'
delta_table: 
  delta_table_path : "data/scmp-stage-layer/cpo/ba_dmnd_data_sdk_fulldata"
  delta_table_source_path : "data/scmp-raw-layer/cpo/cpis/ba_dmnd_data/year=2024/month=8/day=7/ba_dmnd_data_20240807.parquet"
