version: '3.8'

services:
  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: esther
      MINIO_ROOT_PASSWORD: estheresther
    networks:
      - lakehouse-nw
    command: server /data --console-address ":9001"
    volumes:
      - minio-data:/data
  # delta-app:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: delta-app
  #   networks:
  #     - lakehouse-nw
  #   volumes:
  #     - ./delta_lake/src:/src
  #   entrypoint: ["python3","/src/acid.py"]

volumes:
  minio-data:

networks:
  lakehouse-nw:
    driver: bridge

