# ###########################################
# # Notebook - Iceberg - Nessie Setup
# ###########################################

# version: "3"

# services:
#   # Spark Notebook Server
#   notebook:
#     image: alexmerced/spark33-notebook
#     container_name: notebook
#     privileged: true
#     networks:
#       - iceberghw
#     volumes:
#       - ./warehouse:/home/docker/warehouse
#       - ./notebooks:/home/docker/notebooks
#       - ./datasets:/home/docker/datasets
#     environment:
#       - AWS_ACCESS_KEY_ID=admin
#       - AWS_SECRET_ACCESS_KEY=password
#       - AWS_REGION=us-east-1
#       - AWS_DEFAULT_REGION=us-east-1
#     ports:
#       - 8888:8888
#       - 8080:8080
#       - 10000:10000
#       - 10001:10001
#   # Nessie Catalog Server Using In-Memory Store
#   nessie:
#     image: projectnessie/nessie:0.67.0
#     container_name: nessie
#     networks:
#       - iceberghw
#     ports:
#       - 19120:19120
#   # Minio Storage Server
#   minio:
#     image: minio/minio:latest
#     container_name: minio_iceberg
#     environment:
#       - MINIO_ROOT_USER=esther
#       - MINIO_ROOT_PASSWORD=estheresther
#       - MINIO_DOMAIN=local
#     networks:
#       - iceberghw
#     ports:
#       - 9001:9001
#       - 9000:9000
#     command: ["server", "/data", "--console-address", ":9001"]
#   # Dremio
#   dremio:
#     # platform: linux/amd64
#     image: dremio/dremio-oss:latest
#     privileged: true
#     ports:
#       - 9047:9047
#       - 31010:31010
#       - 32010:32010
#     container_name: dremio
#     networks:
#       - iceberghw
# networks:
#   iceberghw:
#     driver: bridge
version: '3.8'

services:
  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: esther
      MINIO_ROOT_PASSWORD: estheresther
    networks:
      - lakehouse-nw
    command: server /data --console-address ":9001"
    volumes:
      - minio-data:/data
  
  
  spark-iceberg:
      image: tabulario/spark-iceberg:latest
      container_name: spark-iceberg
      # build: spark/
      networks:
        - lakehouse-nw
      depends_on:
        - rest
        - minio
      volumes:
        - ./iceberg:/home/iceberg/warehouse
        - ./iceberg/src:/home/iceberg/notebooks/notebooks
      environment:
        - AWS_ACCESS_KEY_ID=esther
        - AWS_SECRET_ACCESS_KEY=estheresther
        - AWS_REGION=local
        - AWS_DEFAULT_REGION=local
      ports:
        - 8888:8888
        - 8080:8080
        - 10000:10000
        - 10001:10001
  rest:
    image: tabulario/iceberg-rest:latest
    container_name: iceberg-rest
    networks:
      - lakehouse-nw
    ports:
      - 8181:8181
    environment:
      - AWS_ACCESS_KEY_ID=esther
      - AWS_SECRET_ACCESS_KEY=estheresther
      - AWS_REGION=local
      - AWS_DEFAULT_REGION=local
      - CATALOG_WAREHOUSE=s3://iceberg/
      - CATALOG_IO__IMPL=org.apache.iceberg.aws.s3.S3FileIO
      - CATALOG_S3_ENDPOINT=http://minio:9000


networks:
  lakehouse-nw:
    driver: bridge

