# Dockerfile.trino

FROM trinodb/trino:latest

# Set Java Home environment variable to point to host's Java installation
ENV JAVA_HOME /usr/lib/jvm/java-11-openjdk-amd64

# Optionally, add Java bin directory to PATH
ENV PATH $JAVA_HOME/bin:$PATH
